dataset: ascadv1-variable
supervised_train_steps: 40000
supervised_htune_trial_count: 50
all_classifiers_pretrain_steps: 20000
all_train_steps: 20000
all_classifiers_pretrain_htune_trial_count: 10
all_htune_trial_count: 40
default_kwargs: {}
supervised_training_kwargs:
  classifier_name: mlp-1d
classifiers_pretrain_kwargs:
  classifiers_name: mlp-1d
  classifiers_kwargs:
    input_dropout: 0.0
    hidden_dropout: 0.0
    output_dropout: 0.0
all_kwargs:
  classifiers_name: mlp-1d
  classifiers_kwargs:
    input_dropout: 0.0
    hidden_dropout: 0.0
    output_dropout: 0.0