dataset: ascadv1-fixed
all_classifiers_pretrain_steps: 10000
all_train_steps: 20000
all_htune_trial_count: 1000
default_kwargs:
  classifiers_name: mlp-1d
classifiers_pretrain_kwargs:
  theta_lr: 1.e-3
supervised_training_kwargs:
  classifier_name: mlp-1d
  lr: 1.e-3
all_kwargs:
  theta_lr: 1.e-5
  etat_lr: 1.e-3