dataset: dpav4
supervised_train_steps: 10000
supervised_htune_trial_count: 50
all_classifiers_pretrain_steps: 10000
all_train_steps: 10000
all_classifiers_pretrain_htune_trial_count: 0
all_htune_trial_count: 50
default_kwargs: {}
supervised_training_kwargs:
  classifier_name: mlp-1d
classifiers_pretrain_kwargs:
  classifiers_name: mlp-1d
all_kwargs:
  classifiers_name: mlp-1d